services:
  mirth-connect:
    image: ghcr.io/263man/mirth-connect:4.5.2
    container_name: mirth-connect
    ports:
      - "8443:8443"
      - "6661:6661"
    volumes:
      - mirth-data:/opt/mirth-connect/appdata
    environment:
      - TZ=Europe/Amsterdam
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:8443"] # -k allows insecure connections
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  mirth-invite-engine-api:
    container_name: mirth-invite-engine-api
    build:
      context: ./src/MirthInviteEngine
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      mirth-connect:
        condition: service_healthy

volumes:
  mirth-data: