name: 'Build and Publish Mirth Connect Image'

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    name: 'Build and Push to GHCR'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: 'Check out the repository'
        uses: actions/checkout@v4

      - name: 'Log in to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build and push Docker image'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/mirth/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:4.5.2.b363
          build-args: |
            MIRTH_VERSION=4.5.2.b363